name: Build APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    
      # Checkout the code from the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      # Install necessary dependencies
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip python3-dev build-essential libssl-dev libffi-dev libsqlite3-dev git
          python3 -m pip install --upgrade pip
          python3 -m pip install buildozer==2.0.0 python-for-android==2022.5.9

      # Clean previous build (if any)
      - name: Clean previous build
        run: |
          cd /home/runner/work/podskazka/podskazka
          buildozer android clean

      # Ensure necessary directories exist
      - name: Ensure necessary directories
        run: |
          mkdir -p /home/runner/work/podskazka/podskazka/.buildozer/android/platform/python-for-android
          mkdir -p /home/runner/work/podskazka/podskazka/.buildozer/android/platform/build-arm64-v8a

      # Install python-for-android
      - name: Install python-for-android
        run: |
          python3 -m pip install python-for-android

      # Build APK
      - name: Build APK with Buildozer
        run: |
          cd /home/runner/work/podskazka/podskazka
          buildozer -v android debug

      # Upload the generated APK as an artifact (optional)
      - name: Upload APK as artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-debug.apk
          path: /home/runner/work/podskazka/podskazka/.buildozer/android/platform/build-arm64-v8a/bin/app-debug.apk
