name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Java JDK
      - name: Set up Java 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'temurin'

      # Install Android SDK
      - name: Install Android SDK
        run: |
          # Create Android SDK directory
          mkdir -p $HOME/Android/cmdline-tools
          cd $HOME/Android
          
          # Download and extract command-line tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip
          unzip commandlinetools-linux-7583922_latest.zip -d cmdline-tools
          
          # Move extracted folder to correct location
          mv $HOME/Android/cmdline-tools/cmdline-tools $HOME/Android/cmdline-tools/latest

          # Accept licenses and install SDK components
          yes | $HOME/Android/cmdline-tools/latest/bin/sdkmanager --licenses
          $HOME/Android/cmdline-tools/latest/bin/sdkmanager --sdk_root=$HOME/Android --install \
            "platform-tools" \
            "platforms;android-31" \
            "build-tools;30.0.3" \
            "ndk;21.3.6528147" \
            "extras;android;m2repository"
          
          # Set environment variables for Android SDK
          echo "export ANDROID_HOME=$HOME/Android" >> $GITHUB_ENV
          echo "export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$ANDROID_HOME/tools/bin:$PATH" >> $GITHUB_ENV

      # Install Buildozer dependencies and Cython
      - name: Install Buildozer dependencies and Cython
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential python3-dev python3-pip
          pip3 install buildozer cython

      # Run Buildozer to build APK
      - name: Build APK with Buildozer
        run: |
          buildozer android debug
