name: CI
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      # used to cache dependencies with a timeout
      - name: Get Date
        id: get-date
        
        run: |
        
           echo "::set-output name=date::$(/bin/date -u "+%Y%m%d")"
        shell: bash

      - name: Cache Buildozer global directory
        uses: actions/cache@v4
        with:
          path: .buildozer_global
          key: buildozer-global-${{ hashFiles('buildozer.spec') }} # Replace with your path

      - uses: actions/cache@v4
        with:
          path: .buildozer
          key: ${{ runner.os }}-${{ steps.get-date.outputs.date }}-${{ hashFiles('buildozer.spec') }}

      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          command: buildozer android debug
          buildozer_version: master

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: ${{ steps.buildozer.outputs.filename }}
          name: Build APK

on:
  push:
    branches:
      - main  # Укажите ветку, для которой нужно запускать процесс

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. Проверить репозиторий
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Установить зависимости
    - name: Set up environment
      run: |
        sudo apt update
        sudo apt install -y libffi-dev libssl-dev python3-dev python3-pip git zip unzip
        pip install --upgrade pip
        pip install buildozer

    # 3. Установить Android SDK
    - name: Install Android SDK
      run: |
        mkdir -p $HOME/.buildozer/android/platform
        cd $HOME/.buildozer/android/platform
        wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
        unzip commandlinetools-linux-9477386_latest.zip -d cmdline-tools
        mv cmdline-tools $HOME/.buildozer/android/platform/cmdline-tools/latest
        yes | $HOME/.buildozer/android/platform/cmdline-tools/latest/bin/sdkmanager --sdk_root=$HOME/.buildozer/android/platform/android-sdk \
          "platform-tools" "build-tools;31.0.0" "platforms;android-31"

    # 4. Сборка приложения
    - name: Build APK
      run: |
        cd $GITHUB_WORKSPACE
        buildozer android debug
