Sirazh:
- name: Install Android SDK
  run: |
    mkdir -p $HOME/Android
    cd $HOME/Android
    wget https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip
    unzip commandlinetools-linux-7583922_latest.zip
    $HOME/Android/cmdline-tools/bin/sdkmanager --sdk_root=$HOME/Android --licenses
    $HOME/Android/cmdline-tools/bin/sdkmanager --sdk_root=$HOME/Android --install "platform-tools" "platforms;android-31" "build-tools;30.0.3" "ndk;21.3.6528147" "extras;android;m2repository"

    if [ ! -f "$HOME/Android/build-tools/30.0.3/aidl" ]; then
      echo "AIDL not found, installing build-tools 30.0.3"
      $HOME/Android/cmdline-tools/bin/sdkmanager --sdk_root=$HOME/Android --install "build-tools;30.0.3"
    fi
    echo "export ANDROID_HOME=$HOME/Android" >> $GITHUB_ENV
    echo "export PATH=$ANDROID_HOME/cmdline-tools/bin:$ANDROID_HOME/platform-tools:$ANDROID_HOME/tools/bin:$PATH" >> $GITHUB_ENV

name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Java JDK
      - name: Set up Java 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'

      # Install Android SDK
      - name: Install Android SDK
        run: |
          # Create Android SDK directory
          mkdir -p $HOME/Android
          cd $HOME/Android
          
          # Download and extract command-line tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip
          unzip commandlinetools-linux-7583922_latest.zip
          
          # Accept licenses for SDK components
          echo y | $HOME/Android/cmdline-tools/bin/sdkmanager --licenses
          
          # Install necessary SDK components
          $HOME/Android/cmdline-tools/bin/sdkmanager --sdk_root=$HOME/Android --install "platform-tools" "platforms;android-31" "build-tools;30.0.3" "ndk;21.3.6528147" "extras;android;m2repository"
          
          # Check if AIDL is available and install necessary build-tools if not found
          if [ ! -f "$HOME/Android/build-tools/30.0.3/aidl" ]; then
            echo "AIDL not found, installing build-tools 30.0.3"
            $HOME/Android/cmdline-tools/bin/sdkmanager --sdk_root=$HOME/Android --install "build-tools;30.0.3"
          fi
          
          # Set environment variables for Android SDK
          echo "export ANDROID_HOME=$HOME/Android" >> $GITHUB_ENV
          echo "export PATH=$ANDROID_HOME/cmdline-tools/bin:$ANDROID_HOME/platform-tools:$ANDROID_HOME/tools/bin:$PATH" >> $GITHUB_ENV

      # Install Buildozer dependencies and build APK
      - name: Install Buildozer dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential python3-dev python3-pip
          pip3 install buildozer

      # Run Buildozer to build APK
      - name: Build APK with Buildozer
        run: |
          buildozer android debug
