name: Buildozer Android Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Шаг 1: Клонирование репозитория
    - name: Checkout code
      uses: actions/checkout@v3

    # Шаг 2: Установка зависимостей
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y \
          python3 python3-pip python3-setuptools python3-venv git zip unzip openjdk-11-jdk wget curl

        pip install --upgrade buildozer cython

    # Шаг 3: Установка Android SDK с использованием GitHub Action
    - name: Setup Android SDK
      uses: react-native-community/github-actions/setup-android-sdk@v2
      with:
        android-sdk-version: 31
        ndk-version: 21.3.6528147

    # Шаг 4: Сборка APK с Buildozer
    - name: Build APK
      run: |
        buildozer android debug
