name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Шаг 1: Клонирование репозитория
    - name: Checkout repository
      uses: actions/checkout@v2

    # Шаг 2: Установка Python
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    # Шаг 3: Установка зависимостей для сборки
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y autoconf libtool build-essential
        sudo apt-get install -y python3-dev python3-pip
        sudo apt-get install -y unzip
        sudo apt-get install -y openjdk-8-jdk

    # Шаг 4: Установка Buildozer
    - name: Install Buildozer
      run: |
        python3 -m pip install --upgrade pip
        pip install buildozer

    # Шаг 5: Очистка старой сборки (если необходимо)
    - name: Clean previous build
      run: |
        cd /home/runner/work/podskazka/podskazka
        buildozer android clean

    # Шаг 6: Сборка APK
    - name: Build APK with Buildozer
      run: |
        cd /home/runner/work/podskazka/podskazka
        buildozer android debug --debug
