name: Buildozer Android Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Шаг 1: Клонирование репозитория
    - name: Checkout code
      uses: actions/checkout@v3

    # Шаг 2: Установка зависимостей
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y \
          python3 python3-pip python3-setuptools python3-venv git zip unzip openjdk-11-jdk wget
        pip install --upgrade buildozer cython

    # Шаг 3: Установка Android SDK
    - name: Install Android SDK
      run: |
        mkdir -p $HOME/.buildozer/android/platform
        cd $HOME/.buildozer/android/platform
        wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
        mkdir cmdline-tools
        unzip -q commandlinetools-linux-9477386_latest.zip -d cmdline-tools
        mv cmdline-tools/cmdline-tools $HOME/.buildozer/android/platform/cmdline-tools/latest
        $HOME/.buildozer/android/platform/cmdline-tools/latest/bin/sdkmanager --sdk_root=$HOME/.buildozer/android/platform/android-sdk \
          "platform-tools" "build-tools;31.0.0" "platforms;android-31"

    # Шаг 4: Сборка APK
    - name: Build APK
      run: |
        buildozer android debug
