on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Build APK
        uses: digreatbrian/buildozer-action@v2
        with:
          python-version: 3.8
          buildozer-cmd: buildozer -v android debug

      - name: Check config.log
        if: failure() # Выполняется только при ошибке предыдущего шага
        run: |
          cat /home/runner/work/podskazka/podskazka/.buildozer/android/platform/build-armeabi-v7a_arm64-v8a/build/other_builds/freetype/arm64-v8a__ndk_target_19/freetype/builds/unix/config.log
      
      - name: Upload artifacts
        if: always() # Выполняется даже при ошибке
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: ./bin/*.apk
