name: Build APK

on:
  push:
    branches:
      [ main]
  

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      # Шаг: Проверка последней версии репозитория
      
       - uses: actions/checkout@v4

      - name: Build APK
      uses: digreatbrian/buildozer-action@v2
      with:
      python-version:3.8
      buildozer-cmd: bulldozer -v android debug
      -name: Upload artifacts
uses: actions/upload-artifact@v4 
with: 
name: package 
path: ./bin/*.apk
