name: Buildozer Android Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y python3 python3-pip python3-setuptools python3-venv git zip unzip openjdk-11-jdk wget curl
        pip install --upgrade buildozer cython

    - name: Install Android SDK
      run: |
        mkdir -p $HOME/Android
        cd $HOME/Android
        wget https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip
        unzip commandlinetools-linux-7583922_latest.zip
        yes | $HOME/Android/cmdline-tools/bin/sdkmanager --sdk_root=$HOME/Android --licenses  # Принимаем лицензии
        yes | $HOME/Android/cmdline-tools/bin/sdkmanager --sdk_root=$HOME/Android --install "platform-tools" "platforms;android-31" "build-tools;30.0.3" "ndk;21.3.6528147" "extras;android;m2repository"
        if [ ! -f "$HOME/Android/build-tools/30.0.3/aidl" ]; then
          echo "AIDL not found, installing build-tools 30.0.3"
          yes | $HOME/Android/cmdline-tools/bin/sdkmanager --sdk_root=$HOME/Android --install "build-tools;30.0.3"
        fi
        echo "export ANDROID_HOME=$HOME/Android" >> $GITHUB_ENV
        echo "export PATH=$ANDROID_HOME/cmdline-tools/bin:$ANDROID_HOME/platform-tools:$ANDROID_HOME/tools/bin:$PATH" >> $GITHUB_ENV

    - name: Build APK
      run: |
        buildozer android debug
